// Array con los productos 
const productos_file = [
  {
    id: 1,
    nombre: "Marvo k656",
    categoria: "Teclados",
    precio: 5800,
    stock: 5,
    img: "../Css And Src/src productss/teclados/marvo_1.png",
  },
  {
    id: 22,
    nombre: "Nisuta DS501",
    categoria: "Auriculares",
    precio: 6833,
    stock: 86,
    img: "../Css And Src/src productss/auriculares/nisuta_3.png",
  },

  {
    id: 4,
    nombre: "Logitech K835 TKL",
    categoria: "Teclados",
    precio: 22000,
    stock: 21,
    img: "../Css And Src/src productss/teclados/logitech_1.png",
  },
  {
    arreglo: "cuatro",
    id: 5,
    nombre: "AMD RYZEN 3 3200G",
    categoria: "Componentes",
    precio: 77800,
    stock: 13,
    img: "../Css And Src/src productss/componentes/amd_ryzen_3_2.png",
  },
  {
    id: 3,
    nombre: "Hyperx Alloy Fps",
    categoria: "Teclados",
    precio: 51000,
    stock: 14,
    img: "../Css And Src/src productss/teclados/hyperx_1.png",
  },
  {
    id: 6,
    nombre: "AMD Ryzen 7 PRO 4750G",
    categoria: "Componentes",
    precio: 135000,
    stock: 4,
    img: "../Css And Src/src productss/componentes/amd_ryzen_7_pro_2.png",
  },
  {
    arreglo: "juegos",
    id: 34,
    nombre: "Minecraft PS4 Físico",
    categoria: "Juegos",
    precio: 13999,
    stock: 21,
    img: "../Css And Src/src productss/juegos/minecraft_6.jpg",
  },
  {
    id: 7,
    nombre: "AMD Ryzen 7 7700",
    categoria: "Componentes",
    precio: 250000,
    stock: 8,
    img: "../Css And Src/src productss/componentes/amd_ryzen_7_2.png",
  },
  {
    id: 8,
    nombre: "Intel Pentium Gold",
    categoria: "Componentes",
    precio: 39000,
    stock: 9,
    img: "../Css And Src/src productss/componentes/ntel_pentium_2.png",
  },

  {
    id: 10,
    nombre: "Gigabyte A520M",
    categoria: "Componentes",
    precio: 45490,
    stock: 41,
    img: "../Css And Src/src productss/componentes/mother_gigabyte_2.png",
  },
  {
    arreglo: "dos",
    id: "2",
    nombre: "Kurama K552",
    categoria: "Teclados",
    precio: 23000,
    stock: 3,
    img: "../Css And Src/src productss/teclados/kuramaxd_1.png",
  },
  {
    id: 11,
    nombre: "Asrock B560M Steel Legend",
    categoria: "Componentes",
    precio: 128999,
    stock: 6,
    img: "../Css And Src/src productss/componentes/mother_asrock_2.png",
  },
  {
    id: 12,
    nombre: "SuprimX GeForce RTX 3090",
    categoria: "Componentes",
    precio: 1280000,
    stock: 2,
    img: "../Css And Src/src productss/componentes/suprimx_geforce_2.png",
  },

  {
    id: 14,
    nombre: "Corsair DDR4 8GB",
    categoria: "Componentes",
    precio: 14650,
    stock: 21,
    img: "../Css And Src/src productss/componentes/ram_corsair_2.png",
  },
  {
    id: 15,
    nombre: "OLOy DDR4 16GB",
    categoria: "Componentes",
    precio: 39069,
    stock: 22,
    img: "../Css And Src/src productss/componentes/ram_oloy_2.png",
  },
  {
    id: 24,
    nombre: "RedDragon Griffin",
    categoria: "Mouses",
    precio: 9238,
    stock: 7,
    img: "../Css And Src/src productss/mouses/reddragon_griffin_4.png",
  },
  {
    id: 29,
    nombre: "Adaptador Hdmi a DisplayPort",
    categoria: "Cables",
    precio: 2560,
    stock: 15,
    img: "../Css And Src/src productss/cables/adaptador_5.png",
  },
  {
    id: 17,
    nombre: "Aerocool Cylon 700W",
    categoria: "Componentes",
    precio: 33800,
    stock: 16,
    img: "../Css And Src/src productss/componentes/fuente_cyclon_2.png",
  },
  {
    id: 18,
    nombre: "Corsair Crystal 680X",
    categoria: "Componentes",
    precio: 141000,
    stock: 12,
    img: "../Css And Src/src productss/componentes/gabinete_corsair_2.png",
  },
  {
    arreglo: "tres",
    id: 19,
    nombre: "Cooler CPU Deepcool",
    categoria: "Componentes",
    precio: 9999,
    stock: 25,
    img: "../Css And Src/src productss/componentes/cooler_2.png",
  },
  {
    id: 20,
    nombre: "Logitech G733",
    categoria: "Auriculares",
    precio: 60395,
    stock: 21,
    img: "../Css And Src/src productss/auriculares/logitech_3.png",
  },
  {
    id: 21,
    nombre: "Red Dragon ZEUS H510",
    categoria: "Auriculares",
    precio: 28917,
    stock: 7,
    img: "../Css And Src/src productss/auriculares/reddragon_3.png",
  },
  {
    arreglo: "juegos",
    id: 35,
    nombre: "Need For Speed",
    categoria: "Juegos",
    precio: 7698,
    stock: 12,
    img: "../Css And Src/src productss/juegos/nfs_6.jpg",
  },
  {
    id: 23,
    nombre: "HyperX Cloud Stin",
    categoria: "Auriculares",
    precio: 69999,
    stock: 17,
    img: "../Css And Src/src productss/auriculares/hyperx_3.png",
  },
  {
    id: 25,
    nombre: "RedDragon Cobra",
    categoria: "Mouses",
    precio: 16250,
    stock: 23,
    img: "../Css And Src/src productss/mouses/reddragon_cobra_4.png",
  },
  {
    id: 26,
    nombre: "Logitech G403",
    categoria: "Mouses",
    precio: 21000,
    stock: 61,
    img: "../Css And Src/src productss/mouses/logitech_g403_4.png",
  },
  {
    id: 27,
    nombre: "Logitech G904",
    categoria: "Mouses",
    precio: 49999,
    stock: 34,
    img: "../Css And Src/src productss/mouses/logitech_g904_4.png",
  },
  {
    arreglo: "juegos",
    id: 32,
    nombre: "Black ops III",
    categoria: "Juegos",
    precio: 800,
    stock: 92,
    img: "../Css And Src/src productss/juegos/bo3_6.webp",
  },
  {
    id: 28,
    nombre: "Cable HDMI 2 Mts",
    categoria: "Cables",
    precio: 2560,
    stock: 31,
    img: "../Css And Src/src productss/cables/hdmi_5.png",
  },
  {
    id: 13,
    nombre: "MSI GeForce RTX 3090 24GB",
    categoria: "Componentes",
    precio: 930650,
    stock: 11,
    img: "../Css And Src/src productss/componentes/msi_geforce_2.png",
  },
  {
    id: 30,
    nombre: "Cable Ethernet 5 Mts",
    categoria: "Cables",
    precio: 2365,
    stock: 40,
    img: "../Css And Src/src productss/cables/ethernet_5.png",
  },
  {
    arreglo: "juegos",
    id: 36,
    nombre: "Assasins Creed IV",
    categoria: "Juegos",
    precio: 7999,
    stock: 31,
    img: "../Css And Src/src productss/juegos/assasins_6.webp",
  },
  {
    id: 31,
    nombre: "Cable Fuente 3 Mts",
    categoria: "Cables",
    precio: 1399,
    stock: 12,
    img: "../Css And Src/src productss/cables/fuente_5.png",
  },
  {
    id: 9,
    nombre: "Intel Core i5",
    categoria: "Componentes",
    precio: 100000,
    stock: 1,
    img: "../Css And Src/src productss/componentes/intel_core_2.png",
  },

  {
    arreglo: "juegos",
    id: 33,
    nombre: "GTA V",
    categoria: "Juegos",
    precio: 1099,
    stock: 52,
    img: "../Css And Src/src productss/juegos/gtav_6.webp",
  },
  {
    id: 16,
    nombre: "SSD Kingston 960GB",
    categoria: "Componentes",
    precio: 26999,
    stock: 2,
    img: "../Css And Src/src productss/componentes/ssd_2.png",
  },
];


